### ISSUE TITLE
As a user, the new issue type icons should not appear as broken pictures icons.

### ISSUE THREAD

**Issue by cturkle** [mailru/jira-plugins-mailrucal#103]
The latest version of Mail.Ru calendar now shows broken icons for all of my calendars regardless of whether the issues were epics, stories, tasks, etc.  Issue icons in our instance have not been altered from the default Jira configuration. Can you tell me how to correct this problem or how to roll back to a previous version?

![image](https://user-images.githubusercontent.com/29930666/27883798-d88aa990-619f-11e7-85f1-aec3e90a9bd3.png)

**Comment by cturkle** [comment]
I rolled back to a previous version, but I'd still like to get an update on whether others have experienced the broken picture icon as noted above and whether there's a fix for it.  I'll keep using version 2.5.9.78 for now, but I know at some point in the future it's possible I'll need/want to upgrade without the broken view.  Thanks in advance for your help!

**Comment by nteplov** [comment]
Hi! That fixed in 3.0.0!
