### ISSUE TITLE
After JIRA update, calendar gadget is strange.

### ISSUE THREAD

**Issue by khj7744** [mailru/jira-plugins-mailrucal#104]
After JIRA 7.3.1 -> 7.4.0 update.
serverurl = example.co.kr/jira

![image](https://user-images.githubusercontent.com/9972100/28150373-17fcd85c-67cf-11e7-95a3-7082702b9b5f.png)
There is a 'ag-sys-msg' at the top of the gadget.
'The resource /jira/rest/webResources/1.0/resources, cannot be found.'

![image](https://user-images.githubusercontent.com/9972100/28150379-1e39944e-67cf-11e7-9789-6932bd6433f2.png)
This image url is /secure/viewavatar?size~
but JIRA v 7.3.1 image url was jira/secure/viewavatar?size~
This image url dose not exist '/jira'

**Comment by nteplov** [comment]
That fixed in 3.0.0
