### ISSUE TITLE
Errors Upgrading to Version 2.1.8

### ISSUE THREAD

**Issue by acasari** [mailru/jira-plugins-mailrucal#11]
JIRA 6.4.9

**Comment by acasari** [comment]
1) Got "undefined" alert window when enter Calendar (attached)
2) Get an exception when saving (attached)
3) Leave Calendar and return, the calendars created are gone.
4) Existing Calendars are not recognized after upgraing from 2.1.3 to 2.1.8

![mailru1](https://cloud.githubusercontent.com/assets/562904/12274020/ac6f55c4-b947-11e5-8c9e-82cf8104b4fd.png)
![mailru](https://cloud.githubusercontent.com/assets/562904/12274019/ac0b8fda-b947-11e5-98f6-62a2b92e66b8.png)

**Comment by mashintsev** [comment]
1) Does it repeat regularly?
2) Can you attach a log for ru.mail.jira.plugins.calendar package?
3) Maybe error occurs on creating the calendar. Please attach logs.
4) If shared calendars are not visible, after upgrading to 2.1.8 they are gone from list. And you can find them by clicking "Add calendar"->"Add shared".

**Comment by acasari** [comment]
1) Everytime.
2,3) Attached.
4) Add shared shows nothing.
[atlassian-jira.zip](https://github.com/mailru/jira-plugins-mailrucal/files/87933/atlassian-jira.zip)

**Comment by mashintsev** [comment]
I find the problem. Tomorrow we will fix it.

**Comment by mashintsev** [comment]
We release new version https://marketplace.atlassian.com/plugins/ru.mail.jira.plugins.mailrucal/versions#b350

**Comment by mashintsev** [comment]
Hello, Adolfo. Do we resolve your problem?

**Comment by acasari** [comment]
Yes, thanks.
