### ISSUE TITLE
Managing of fields visible in Calendar

### ISSUE THREAD

**Issue by UdayaMudigere** [mailru/jira-plugins-mailrucal#13]
Is there a way to display Summary and Reporter in the calendar? Currently only summary is being shown and upon clicking the item, it displays all the data. We are using JIRA 6.4.12

**Comment by mashintsev** [comment]
Yes of course. Just select required fields in "fields" input.
<img width="323" alt="2016-01-14 14 57 01" src="https://cloud.githubusercontent.com/assets/986470/12323773/2ae7fa9a-bacf-11e5-8939-29c8f0b302b5.png">
<img width="633" alt="2016-01-14 14 56 36" src="https://cloud.githubusercontent.com/assets/986470/12323774/2ca1a30e-bacf-11e5-85f4-e6096f76f37a.png">

**Comment by UdayaMudigere** [comment]
I did select it and it will show only Summary on the day of the calendar; upon clicking it, it shows the details of the fields that I selected. When it displays, it shows 10:08: PLease change to Issue type to Enhancement. Once I click on that, Assignee, Reporter and Status are shown. 

What we wanted to see was just Time, Summary and Reporter in the Date section. Is there a way to do it? Please let me know.

See below:

![calendar](https://cloud.githubusercontent.com/assets/16702570/12330346/406cd842-baaa-11e5-83f3-2dedeee8b469.PNG)

**Comment by mashintsev** [comment]
I understand you. We will discuss the enhancement as a team and inform our decision.

**Comment by andreymolchanov** [comment]
So, we do plan to implement the feature. However I can't provide you with exact implementation terms.

**Comment by mashintsev** [comment]
We release 2.1.12 version in which issue ID is provided to the event title. Ability to view other fields in event title we will do in out next release. 
You can download it from here  - https://marketplace.atlassian.com/plugins/ru.mail.jira.plugins.mailrucal/versions
