### ISSUE TITLE
Sort Mail-ru Calendars alphabetically

### ISSUE THREAD

**Issue by Geolap** [mailru/jira-plugins-mailrucal#14]
Hello,
I'm creating one calendar per user of a team. My calendar's name are made like this /[team]-[user].
Once I created all users'calendar of each team, If a new user comes in, the calendar will not be displayed next to it's team but will be added at the end of the list.
I would pretty much like to be able to sort my created calendars alphabetically.
Would it be possible to implement that functionality ?

An other slightly different way to answer this case would be the possibility to set some calendar groups.
I raise another issue later for the groupping option.

Cheers,

**Comment by mashintsev** [comment]
Hi.

Do you want sorting calendars in import dialog or calendar list in right page block?

**Comment by Geolap** [comment]
Hi,

I'm talking about the calendar list on the right pane :
![image](https://cloud.githubusercontent.com/assets/16922458/12717692/beb8efae-c8e9-11e5-9157-f132dc472b0c.png)
I can' see what is the 'import dialog' you are talking about. That may be an alternative for me to export an reimport sorted calendars !

**Comment by mashintsev** [comment]
Now we release 2.1.11 and 2.2.6 version with sorting alphabetically calendars. Check this on https://marketplace.atlassian.com/plugins/ru.mail.jira.plugins.mailrucal/versions.

**Comment by Geolap** [comment]
First view It's great to me.
Thanks a lot for the work.
