### ISSUE TITLE
Display Issue ID on calendar

### ISSUE THREAD

**Issue by vthomas705** [mailru/jira-plugins-mailrucal#16]
When we moved from version 1.6.7 to 2.0 the Issue key was removed from the calendar display.  A reference to the project or Issue key is not displayed anywhere now except the URL of the issue.

Could you add this back or add an option to show/hide issue ID on the calendar page itself, not the onclick pop up.

**Comment by mashintsev** [comment]
We release 2.1.12 version in which this issue is done. You can download it from here - https://marketplace.atlassian.com/plugins/ru.mail.jira.plugins.mailrucal/versions

**Comment by vthomas705** [comment]
This new updates is perfect! Thank you for being so responsive.
