### ISSUE TITLE
Bug with calendar

### ISSUE THREAD

**Issue by rubaliv** [mailru/jira-plugins-mailrucal#17]
Hello,

After installing the new version I have a critical Bug.
Please see the attachment.
![2016-02-05_0851](https://cloud.githubusercontent.com/assets/13197565/12840699/c11aef82-cbe5-11e5-93e2-c6c003cffd75.png)

Our Jira version is the v6.4.11#64026-sha1:78f6ec4 and we use it in french language.

**Comment by mashintsev** [comment]
Hello,
try reinstall or disable/enable plugin. Maybe it's an error during plugin installation.

**Comment by rubaliv** [comment]
Thanks ! It's working.
