### ISSUE TITLE
Undefined Popup Window

### ISSUE THREAD

**Issue by danielkrueger1** [mailru/jira-plugins-mailrucal#18]
We're getting a popup window when we click on the Calendar link in the menubar. All it says is 'undefined'. After we clicked it the screen loaded and none of the calendars were listed.

**Comment by mashintsev** [comment]
Hi.
Specify your Jira and Mail.Ru Calendar versions.
In browser open console and copy all messages.

**Comment by danielkrueger1** [comment]
Were using

  *   JIRA v6.4.11#64026-sha1:78f6ec4
  *   MailRUCal: 2.1.12
  *   Console log is attached.



[https://lacek.hs.llnwd.net/e1/lacek/em_sig/TLG_EM_Red.jpg]

DANIEL KRUEGER  |  Technical Project Manager
The Lacek Group  |  A Specialty Agency of Ogilvy & Mather
P: 612-359-3702

Privileged/Confidential Information may be contained in this message. If you are not the addressee indicated in this message, you should destroy this message. For more information on WPP's business ethical standards and corporate responsibility policies, please refer to WPP's website.



________________________________

**Comment by mashintsev** [comment]
There is no attachment.

**Comment by danielkrueger1** [comment]
Navigated to http://jira.lacek.net/secure/MailRuCalendar.jspa
5.7.31
Deprecation warning: moment.langData is deprecated. Use moment.localeData instead.
Error
    at Function.langData (http://jira.lacek.net/s/ccc70a114db958e3b6468de376235dc6-CDN/en_USn9c3e5/64…s/ru.mail.jira.plugins.mailrucal:calendar-resources.js?locale=en-US:2:9386)
    at http://jira.lacek.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/en_USn9c3e5/64…ocalisation-moment/jira.webresources:calendar-localisation-moment.js:2:134
    at http://jira.lacek.net/s/d41d8cd98f00b204e9800998ecf8427e-CDN/en_USn9c3e5/64…ocalisation-moment/jira.webresources:calendar-localisation-moment.js:2:431
JIRA.Events.NEW_CONTENT_ADDED: 
d.Event {type: "newContentAdded", timeStamp: 1455119815652, jQuery1720010753866285085678: true, isTrigger: true, exclusive: undefined…}currentTarget: documentdata: nulldelegateTarget: documentexclusive: undefinedhandleObj: ObjectisTrigger: truejQuery1720010753866285085678: truenamespace: ""namespace_re: nullresult: undefinedtarget: documenttimeStamp: 1455119815652type: "newContentAdded"__proto__: Object
Your are trying to create a ToggleBlock with selector '.twixi'.One already exists with this trigger so has been ignored.
Your are trying to create a ToggleBlock with selector '.toggle-trigger'.One already exists with this trigger so has been ignored.
Your are trying to create a ToggleBlock with selector '.toggle-trigger'.One already exists with this trigger so has been ignored.
DEPRECATED - Dropdown constructor has been deprecated and will be removed in a future release. Use Dropdown2 instead.  
     at Object.exports.bindConfigDashboardDds (http://jira.lacek.net/s/860c5aa0ce9f12901c70a95b93cf3d53-CDN/en_USn9c3e5/64026/220/58/_/download/superbatch/js/batch.js?locale=en-US:2633:1648)
DEPRECATED - Inline dialog constructor has been deprecated and will be removed in a future release. Use inline dialog 2 instead.  
     at Backbone.View.extend.createDialog (http://jira.lacek.net/s/71d51a76a1e20baf91cb6a00330ce7c3-CDN/en_USn9c3e5/64…disabled_marketing=true&jaguser=true&locale=en-US&hc-enabled=true:3469:812)
BugWatcher watcherpicker.js loaded
in-app notifications polling: [object Object]
polling for notifications
DEPRECATED - Inline dialog constructor has been deprecated and will be removed in a future release. Use inline dialog 2 instead.  
     at Object.BugWatcher.setupNotificationsDialog (http://jira.lacek.net/s/2201f1b12db4434a00a057223b68224e-CDN/en_USn9c3e5/64…l,jira.general/batch.js?content-type=text%2Fjavascript&locale=en-US:4:5419)
30
GET http://jira.lacek.net/rest/mailrucalendar/1.0/calendar/all?_=1455119815780 400 (Bad Request)
polling for notifications
30
polling for notifications
30
polling for notifications
30
polling for notifications
30
polling for notifications
30
polling for notifications
30
polling for notifications
30
polling for notifications
30
polling for notifications
30

**Comment by mashintsev** [comment]
It's server error. Can you attach Jira server logs for package "ru.mail.jira.plugins.calendar".

**Comment by danielkrueger1** [comment]
We're new to JIRA.

On the logging page there was no entry for "ru.mail.jira.plugins.calendar", so I added it manually this morning and clicked into the calendar and got the error message again. I set the level to TRACE and then DEBUG.


We can't seem to find a specific log just for "ru.mail.jira.plugins.calendar", we can only see the main log that has no information about the calendar plugin.


What advice do you have?


Thanks,

Dan


[https://lacek.hs.llnwd.net/e1/lacek/em_sig/TLG_EM_Red.jpg]

DANIEL KRUEGER  |  Technical Project Manager
The Lacek Group  |  A Specialty Agency of Ogilvy & Mather
P: 612-359-3702

Privileged/Confidential Information may be contained in this message. If you are not the addressee indicated in this message, you should destroy this message. For more information on WPP's business ethical standards and corporate responsibility policies, please refer to WPP's website.



________________________________

**Comment by mashintsev** [comment]
Try just search by 'ru.mail.jira.plugins.calendar'

четверг, 11 февраля 2016 г. пользователь danielkrueger1 написал:

> We're new to JIRA.
>
> On the logging page there was no entry for
> "ru.mail.jira.plugins.calendar", so I added it manually this morning and
> clicked into the calendar and got the error message again. I set the level
> to TRACE and then DEBUG.
>
>
> We can't seem to find a specific log just for
> "ru.mail.jira.plugins.calendar", we can only see the main log that has no
> information about the calendar plugin.
>
>
> What advice do you have?
>
>
> Thanks,
>
> Dan
>
>
> [https://lacek.hs.llnwd.net/e1/lacek/em_sig/TLG_EM_Red.jpg]
>
> DANIEL KRUEGER | Technical Project Manager
> The Lacek Group | A Specialty Agency of Ogilvy & Mather
> P: 612-359-3702
>
> Privileged/Confidential Information may be contained in this message. If
> you are not the addressee indicated in this message, you should destroy
> this message. For more information on WPP's business ethical standards and
> corporate responsibility policies, please refer to WPP's website.
>
>
>
> ________________________________
> From: Ivan Mashintsev <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> Sent: Thursday, February 11, 2016 4:40 AM
> To: mailru/jira-plugins-mailrucal
> Cc: Daniel Krueger
> Subject: Re: [jira-plugins-mailrucal] Undefined Popup Window (#18)
>
>
> It's server error. Can you attach Jira server logs for package
> "ru.mail.jira.plugins.calendar".
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/mailru/jira-plugins-mailrucal/issues/18#issuecomment-182800238
> >.
>
>
>
> Privileged/Confidential Information may be contained in this message. If
> you are not the addressee indicated in this message, you should destroy
> this message. For more information on WPP's business ethical standards and
> corporate responsibility policies, please refer to WPP's website.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mailru/jira-plugins-mailrucal/issues/18#issuecomment-182923963>
> .
>


-- 
Best regards,
Ivan Mashintsev

+79165439097
skype: i.mashintsev
facebook.com/mashintsev <http://www.facebook.com/mashintsev>
ru.linkedin.com/in/mashintsev
trip-mashina.ru <http://www.trip-mashina.ru/>

**Comment by danielkrueger1** [comment]
We searched this log; /var/atlassian/application-data/jira/log/atlassian-jira.log

See attachment


[https://lacek.hs.llnwd.net/e1/lacek/em_sig/TLG_EM_Red.jpg]

DANIEL KRUEGER  |  Technical Project Manager
The Lacek Group  |  A Specialty Agency of Ogilvy & Mather
P: 612-359-3702

Privileged/Confidential Information may be contained in this message. If you are not the addressee indicated in this message, you should destroy this message. For more information on WPP's business ethical standards and corporate responsibility policies, please refer to WPP's website.



________________________________

**Comment by mashintsev** [comment]
Daniel, please attach file in github web site. When you attach file in email github doesn't show it.

**Comment by danielkrueger1** [comment]
[rucalendar.zip](https://github.com/mailru/jira-plugins-mailrucal/files/133045/rucalendar.zip)

**Comment by mashintsev** [comment]
You got [atlassian.jira.permission.DefaultPermissionSchemeManager] No permission scheme is associated with project 'SPG Pro Lightbox' exception on server.

You need specify permission scheme for all your projects.

https://confluence.atlassian.com/jira/managing-project-permissions-185729636.html
https://confluence.atlassian.com/jirakb/unable-to-create-new-project-can-t-assign-default-permission-scheme-797573291.html

**Comment by danielkrueger1** [comment]
Symptoms:  when accessing the 'Calendars' section on the JIRA banner (at some unspecific time after integrating the RU.Calendar add-on into JIRA), the webpage displays a Javascript alert stating the text 'undefined'.  Further analysis revealed that the following web request failed:
http://jira.lacek.net/rest/mailrucalendar/1.0/calendar/all?_=1455649862796 
which appears to be a REST API request to the local add-on.  This web request returned the following string: "The project id can not be null".

Resolution:  a naive investigation approach into the JIRA database and records associated with the RU.Calendar add-on revealed the following tables: AO_0DB21A_CALENDAR, AO_0DB21A_SHARE, AO_0DB21A_USER_DATA.  The following records were observed in the SHARE table:
 
CALENDAR_ID 	GROUP 	                ID 	PROJECT 	ROLE
38 	                        Group_name 	        34 	0 	                0
39 	                        Group_name 	        66 	0 	                0
40 	                        Group_name 	        67 	0 	                0
41 	                        Group_name 	        68 	0 	                0
42 	                        Group_name 	        61 	10941 	        10000
43 	                        Starwood 	                62 	13414 	        10000
44 	                        Group_name 	        71 	0 	                 0
50 	                        Group_name 	        76 	0 	                 0
 
Removing the divergent rows from the SHARE table (ID:61, ...) (ID:62, ...); as well as the associated rows in the CALENDAR table (ID:42, ...), (ID:43, ...) repaired the problem of retrieving calendars correctly and the add-on works as intended.
