### ISSUE TITLE
Add Calendar  (automatic shared)

### ISSUE THREAD

**Issue by saschawagner** [mailru/jira-plugins-mailrucal#20]
Is there a way to  share a calendar to jira members or a jira group without having every user  to add this manually? Maybe a function to share a Calendar as default. Or an add user to function or script (possible sql script) This way its more simple to get Jira user to work with the calendar they have to see.   

Jira 6.3
2.1.12

**Comment by mashintsev** [comment]
Hello.
Do you want when sharing a calendar user can specify the option to automatically add a calendar to users?
Now this functionality doesn't exist. We add this issue in our backlog.

**Comment by saschawagner** [comment]
Thank you! yes that's is my intention
Such  would be very helpful  to me so I can assure everyone has an calendar available when sharing a new one. Also save me from many complaint of people not seeing some calendar or even worse people not complaining loudly but being unhappy because ether don't see a calendar. I am aware the just can add this themselves but with people working independently in different location this sometimes gets harder than expected so such thing would simplify things.

**Comment by saschawagner** [comment]
Do you know if this will be implemented sometime soon ? 
Is there maybe a workaround  until its available. Maybe by running some sql statement?

**Comment by andreymolchanov** [comment]
Hi Sasha,

I am unsure about the function of adding calendars to other users automatically, cause some users may not like it all that somebody suddenly changes their calendars list.

Instead we will support URLs containing the information about currently displayed calendars, selected view mode, choosen date and zoom (for timeline mode) and shown or hidden weekends. You will be able to copy the link from your browser and give it to your users. When opening on user browser, it will ask to add all the calendars the user hasn't added yet. Make sure, the calendars are shared to the users using groups or project roles. I think, we will implement this functionality within a month (including many other options).

If this is not suitable for you, I can suggest:
1. Use some plugins that allows JIRA administrator to login under some other user account (Scripting Suite or Teamlead Werewolf) and add existing calendars manually.
2. Modify database (on your own responsibility). @mashintsev can provide you with some information if it is the best solution for you.

Have a nice day! :)

**Comment by saschawagner** [comment]
Hello Andrey, hello Ivan,
sending out a link to users so they and can easily add a calendar sounds like a great solution to me. 
we would be obliged if you could provide some, maybe even sparse information regarding  the database modification.
Thank you very much and have a nice day as well. 
Sascha

**Comment by mashintsev** [comment]
Hi, Sascha.
I will send you database structure tomorrow. And discuss you how add calendar to users by sql.

**Comment by mashintsev** [comment]
Hi.
You need 2 tables - **AO_[HASH]_USER_DATA**, **AO_[HASH]_CALENDAR**. In **...Calendar** table find ids for chosen calendars. To add calendars to the user list you need add ids joined by ";" to column **FAVORITE_CALENDARS** in **...USER_DATA** table. If you want that calendars will be enabled you need add these to column **SHOWED_CALENDARS**.
Example,
**FAVORITE_CALENDARS** - "1;2;3;4;5;7;10"
**SHOWED_CALENDARS** - "1;10;6;3"

**Comment by saschawagner** [comment]
Thank you !
It's working nicely. However there is a field iCal_UID. So when creating a new record I used a random id. 
It's seems working but maybe not the correct way. So do I need to do a lookup from another table ? 
Example for an id I found 89e07ef0
thank you once more.

**Comment by mashintsev** [comment]
iCal_UID is random hash for user to export calendars in ical format. Random hash id is perfect solution for it.
