### ISSUE TITLE
Can't navigate back from calendar

### ISSUE THREAD

**Issue by lexek** [mailru/jira-plugins-mailrucal#21]
**Steps to reproduce:**
1. go to JIRA dashboard
2. click calendar link in JIRA header
3. go back in browser

**Desired behavior:**
Browser will navigate to dashboard.

**Current behavior:**
Browser is still at calendar page.

**Comment by Geolap** [comment]
Hello,
If it can help, with chrome and Jira v6.4.3 and Calendar 2.1.11
When I clic on Go back in browser, I go back to the dashboard.
Chers,
