### ISSUE TITLE
Please add more Collors.

### ISSUE THREAD

**Issue by sesh03141** [mailru/jira-plugins-mailrucal#22]
Hi Folks!
Can you expand the palette?
Thanks!

**Comment by mashintsev** [comment]
How many colors do you need?

**Comment by sesh03141** [comment]
Oh, as much as possible. Or eyedropper - that  will be perfect...

What we have now: 
![image](https://cloud.githubusercontent.com/assets/17544015/13393180/c9883a76-def0-11e5-9b42-79c348b48ab2.png)

**Comment by andreymolchanov** [comment]
I think it would be the best solution to take colors from here: https://design.atlassian.com/product/foundations/colors/ - for each color there are 2 variants - main and highlighted, we will use main version.

Red-Blue colors from the main palette and all the colors from secondary palette (I am not sure about Gray, Ash Gray and Silver though). And for event name Light Gray and Charcoal depending on what is readable better.

**Comment by sesh03141** [comment]
Hi Andrey, number of objects in calendar will increase. Sooner or later we will come back with a request to add a new colors again.

So best solution it is eyedropper.

Thanks!

**Comment by sesh03141** [comment]
Sorry for the audacity, when can we expect to release?

**Comment by andreymolchanov** [comment]
Hi,
About new colors - we expect new release in about 1-2 weeks, I think.
About eyedrop - it won't be released in the next version, but I will add it to the roadmap.

**Comment by sesh03141** [comment]
Hi Andrey,
Ok Got it.

Thanks!

**Comment by sesh03141** [comment]
**Hi Mail.ru Team!**
Please let me to know, when this feature will be raised?
Thanks!

**Comment by mashintsev** [comment]
Hi.
We have realized this feature. And now we are testing version 2.3. I hope that we will have published it at the end of the week.

**Comment by mashintsev** [comment]
Hi, we release new version 2.3.0.44_JIRA6. Check out it [here](https://marketplace.atlassian.com/plugins/ru.mail.jira.plugins.mailrucal/versions#b440).
