### ISSUE TITLE
Issues not appearing on calendar after upgrading Jira

### ISSUE THREAD

**Issue by seanmkeating** [mailru/jira-plugins-mailrucal#25]
Hello,
After upgrading to JIRA 6.4.13, none of the issues show up any more on the calendar. The filter I use to populate the calendar is still working, however. I'm using 2.1.12.

Any ideas?

**Comment by mashintsev** [comment]
Hi, Sean.
Please, provide plugin version. And attach browser console log for this page and Jira server log for package "ru.mail.jira.plugins.calendar".

Tomorrow we locally test plugin on JIRA 6.4.13. Your logs accelerate the analysis of the problem.

**Comment by seanmkeating** [comment]
Thanks for the reply -- members of my team will respond shortly.

**Comment by shuang2206** [comment]
Hello,

Our plugin version is 2.1.12. I am attaching an image of our console log, and a file containing the results of a search done in atlassian-jira.log for 'ru.mail.jira.plugins.'

<img width="1270" alt="screen shot 2016-03-10 at 3 56 24 pm" src="https://cloud.githubusercontent.com/assets/11756857/13684307/1e7a1640-e6d9-11e5-9123-7bd1d5534370.png">


[ru.mail.jira.plugins.txt](https://github.com/mailru/jira-plugins-mailrucal/files/167995/ru.mail.jira.plugins.txt)


Shirley

**Comment by mashintsev** [comment]
With the log I see that there is no custom field for End Date. Check calendar settings dialog and End Date field. Maybe after upgrading JIRA this custom field was deleted.

**Comment by mashintsev** [comment]
Do you still have problem?

**Comment by seanmkeating** [comment]
Hi. Yes. It seems to only work if we set a field for "Event Start" and "Event End" in the Edit Calendar settings. Since we use the plugin for days when we schedule email, we only have a single date (a custom date field "Send Date"). If I just make "Event Start" the Send Date, nothing appears on the calendar. If I make Event Start and Event End both Send Date, it still doesn't show up on the calendar.

If I make Event Start "Created" and Event End "Send Date", the date range does show up on the calendar, but this isn't how we've been using this plugin. Again, all of our events are a single day (the day we send an email).

It did work before, so maybe there was some change it how it's interpenetrating starts and ends?

Thanks for checking back.

**Comment by mashintsev** [comment]
Hi, @seanmkeating, @shuang2206 . I think that is the same problem like #24. In this issue #24 there is attachment with plugin patches.

We will include it in next big release 2.3.

**Comment by mashintsev** [comment]
Hi, we release new version 2.3.0.44_JIRA6. Check out it [here](https://marketplace.atlassian.com/plugins/ru.mail.jira.plugins.mailrucal/versions#b440).

**Comment by seanmkeating** [comment]
The update fixed it for us. Looks great!

Only one small thing to consider for future updates -- changing the navigation name back to just "Calendar". "Mail.Ru Calendar" is a little long on the menu bar. But I'm being picky ... this update is great. Thanks!

**Comment by mashintsev** [comment]
Thanks for your response, Sean.
I'll discuss it with my team.
