### ISSUE TITLE
The datails window is not wide enough to display all data

### ISSUE THREAD

**Issue by mashintsev** [mailru/jira-plugins-mailrucal#26]
I'd like to display the issue status in the details view. Unfortunatelly the view is not wide enough. Could you make the window wider, maybe adjustable or dynamic. The goal would be to see all information at a glance.

Michel Clément

**Comment by mashintsev** [comment]
@MichelClement, can you attach a screenshot with issue popup?

**Comment by MichelClement** [comment]
Hi

Please see the following mouse over screen on a calendar entry:

<img width="359" alt="screen_rucalendar" src="https://cloud.githubusercontent.com/assets/15845904/14112435/f669adaa-f5ce-11e5-8632-995ada3bcbf7.png">

Field status is wrapping but still not wide enough.

Kind regards, Michel

**Comment by mashintsev** [comment]
Thanks. We will plan new release on this or next week.

**Comment by mashintsev** [comment]
Hi, we release new version 2.3.0.44_JIRA6. Check out it [here](https://marketplace.atlassian.com/plugins/ru.mail.jira.plugins.mailrucal/versions#b440).

**Comment by andreymolchanov** [comment]
Michel, is it wide enough now?

**Comment by MichelClement** [comment]
:+1: Yes, many thanks.

Kind regards, Michel
