### ISSUE TITLE
mail.ru Calendar calls external javascript file. Why?

### ISSUE THREAD

**Issue by MichelClement** [mailru/jira-plugins-mailrucal#28]
Hi guys

Why is mail.ru calendar calling external resources?

GET http://top-fwz1.mail.ru/js/code.js HTTP/1.1 
Host: top-fwz1.mail.ru 
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0 
Accept: */* 
Accept-Language: en-US,en;q=0.5 
Accept-Encoding: gzip, deflate 
DNT: 1 
Referer: http://somehost/jira/secure/MailRuCalendar.jspa 
Connection: keep-alive

I would say that this javascript file should be part of the addon, not loaded externally. Additionally, if JIRA is running with SSL/TLS, it won't even work calling a non-SSL site.

Thanks.

Kind regards, Michel

**Comment by mashintsev** [comment]
Hi, Michel.
It's statistic counter like Google Analytics. Surely, it doesn't collect any personal data or private information. All information you can check on top.mail.ru.

And it dynamically choose protocol for top-fwz1.mail.ru/js/code.js. If host use HTTPS it alse choose HTTPS.

**Comment by mashintsev** [comment]
Michel,
Do you accept my answer? Close issue?
