### ISSUE TITLE
Filters not available

### ISSUE THREAD

**Issue by shmishmorshin** [mailru/jira-plugins-mailrucal#33]
I am only able to add a select group of filters.  Not all filters are available regardless of who creates them or whether or not they are private or shared with everyone.  Are there any rules for creating filters or how to search and add filters that are not found?

**Comment by mashintsev** [comment]
Hi.
If you are not provided search query in select field, only 10 filter will show. Write filter name and you will get filters that you want.

**Comment by shmishmorshin** [comment]
I created a filter that is public. I clicked on Create Calendar, and typed in the name of the filter and it can not find it.

**Comment by mashintsev** [comment]
Can you check that it is found on the page [jira domain]/secure/ManageFilters.jspa#filterView=search?

**Comment by shmishmorshin** [comment]
It is showing in that list of filters

**Comment by mashintsev** [comment]
Ok. It's a bug and we will fix it.

**Comment by mashintsev** [comment]
One more question.  Did some filters displayed when you search by filter full name in Calendar dialog? And none of them is desired?

**Comment by shmishmorshin** [comment]
There were filters that would show or change as I typed in the name of one I was looking for.  However we have several filters that we use and can not find when trying to create a new calendar.

**Comment by mashintsev** [comment]
Hi, we release new version 2.3.0.44_JIRA6. Check out it [here](https://marketplace.atlassian.com/plugins/ru.mail.jira.plugins.mailrucal/versions#b440).
