### ISSUE TITLE
Suggest user filters at the first place

### ISSUE THREAD

**Issue by mashintsev** [mailru/jira-plugins-mailrucal#38]
User's and favorite filter if no query is provided. And show first them otherwise.

- [x] ~~Filter picker group name is not shown~~
- [x] ~~Filter picker shows me 585 of 591 filters when search for "f" letter - quite a strange optimization~~
- [x] ~~Test "Unavailable filter"~~
- [x] ~~Let's separately display 2 groups: Favorite filters and My filters. Duplicates are allowed.~~
- [x] ~~Search by "f"~~

**Comment by andreymolchanov** [comment]
- [ ] Filter picker group name is not shown
- [ ] Filter picker shows me 585 of 591 filters when search for "f" letter - quite a strange optimization
- [ ] Test "Unavailable filter"
