### ISSUE TITLE
Calendar fullscreen mode

### ISSUE THREAD

**Issue by mashintsev** [mailru/jira-plugins-mailrucal#41]
Add button "View in fullscreen" near "Show/Hide weekends" button.

Bugs:
- [x] ~~View mode popup is overflown by the full screen button when focused~~
- [x] ~~Try to scrollDown, but fadeIn animation~~
- [x] ~~Process paddings animation~~

**Comment by andreymolchanov** [comment]
- [ ] View mode popup is overflown by the full screen button when focused
- [ ] Try to scrollDown, but fadeIn animation

**Comment by andreymolchanov** [comment]
- [ ] Timeline should be height 100% when in fullscreen
- [ ] Bug: Enter fullscreen mode -> resize window -> Exit fullscreen mode => All items in the header are collapsed until the next window resize
