### ISSUE TITLE
 Issues is not displayed corectly if calendar start - end date are longer than 2 months.

### ISSUE THREAD

**Issue by Macma77** [mailru/jira-plugins-mailrucal#42]
Issues is not displayed in calendar when start month is less than current month and end month is more than current month.

**Comment by mashintsev** [comment]
Hi.
Could you attach a screenshot with this problem?

**Comment by Macma77** [comment]
When one switch eg. from quarter view to month view issue is not displayed 
![quarter](https://cloud.githubusercontent.com/assets/18414355/14455781/9d8ef2de-00a1-11e6-8b8a-325458ff80e1.png)
![month](https://cloud.githubusercontent.com/assets/18414355/14455784/a11b6be4-00a1-11e6-94ff-62cee818748c.png)

**Comment by mashintsev** [comment]
We release 2.4 version of our plugin. In this version we fixed your problem. You can download it from here.

**Comment by mashintsev** [comment]
Hi, @Macma77.
Have you updated our plugin to 2.4.2.50 version? Can you check your problem and close or reopen this isuue?
