### ISSUE TITLE
Problem with the pluggin title in jira menu

### ISSUE THREAD

**Issue by rubaliv** [mailru/jira-plugins-mailrucal#43]
Hello Support,
Since I have installed the last version the title of the pluggin has changed in the jira menu...why it is "Mail.ru calendar" and not "calandar" ? (See attachment)

Regards,

Olivier
![2016-04-12_1050](https://cloud.githubusercontent.com/assets/13197565/14454824/85e1d7c8-009c-11e6-899a-e65875436e43.png)

**Comment by mashintsev** [comment]
Hi, Oliver.
We change back it in the next release - version 2.4.

**Comment by rubaliv** [comment]
Ok Thank you.
However it'll be great to be able to edit the title in the menu :)

**Comment by mashintsev** [comment]
Check out [new version](https://marketplace.atlassian.com/plugins/ru.mail.jira.plugins.mailrucal/versions#b460) with fix.
