### ISSUE TITLE
Mail.Ru All Dates off by 1 Day

### ISSUE THREAD

**Issue by mashintsev** [mailru/jira-plugins-mailrucal#46]
Source: https://answers.atlassian.com/questions/38396837/mail.ru-all-dates-off-by-1-day

A ticket has a Due Date of: 04/20/16

But it is showing on the Calendar as being 04/19/2016.

 
Everything on the Calendar is like this... off by 1 day.

Any ideas?

JIRA Project Management Software (v7.1.1#71004-sha1:d6b2c0d)

**Comment by ErikBLS** [comment]
I have one user at my company having the same issue. When I simulate her groups and permissions, I can view the calendar as intended. But when she is logged in, the calendar shows everything one day earlier than intended.

**Comment by mashintsev** [comment]
We release 2.4 version of our plugin. In this version we fixed your problem. You can download it from here.

**Comment by ErikBLS** [comment]
Thank you, but the new update appears to be for JIRA version 6. Do you have an update and bugfix for JIRA 7?

**Comment by mashintsev** [comment]
Just released.
