### ISSUE TITLE
Marketplace page

### ISSUE THREAD

**Issue by andreymolchanov** [mailru/jira-plugins-mailrucal#48]
- Marketplace
  - Описание
    - Что такое вкратце еще раз
    - Примеры использования (можно планировать отпуска, отслеживать due date, согласования, что-то еще)
    - Языки
    - OpenSource
    - Версия для JIRA6
  - Скриншоты
    - Screenshot of the calendar page with several calendars enabled
      - Share calendars with your team
      - Calendars are based on issues and their field values. 
    - Screenshot of the gadget with week mode
      - Add 
    - Logotypes of Outlook, Google Calendars, Apple Calendar, iCal on cropped version; Our export dialog on the full version  
      - Export issues using iCal
      - Subscribe to created calendars using your calendar application
    - Timeline and different views 
    - IssueData Popup
    - DragDrop
  - Отдать грамматику на проверку
- GitHub
  - readme
  - делаем jira6 дополнительной веткой, а jira7 основной (не забыть перенастроить bamboo)

**Comment by dariarostshina** [comment]
Плагин позволяет отображать список задач в формате календаря. Продолжительность событий определяется с помощью значений настраиваемых полей.
Особенности данного продукта:
- Множество режимов отображения: квартальный, месячный, дневной и почасовой
- Режим отображения на весь экран
- Возможность сделать календарь домашней страницей в JIRA
- Просмотр календаря в гаджете на рабочем столе
- Возможность скрывать выходные дни
- Отображение деталей задачи в информационном попапе
- Расшаривание календаря другим пользователям
- Изменение интервала событий с помощью Drag & Drop
- Экспорт календарей в различные приложения: Outlook, iCalendar, iOS Calendar, Google Calendar

Плагин позволяет отслеживать различные события в повседневной работе. Это могут быть даты релиза продукта, сроки поставленных задач, отпуска сотрудников и многое другое.
В настоящее время поддерживается два языка интерфейса - английский и русский. Мы будет рады вашей помощи в переводе на ваш язык!
Плагин распространяется с бесплатной лицензией и имеет открытый исходный код, с которым можно ознакомиться здесь - https://github.com/mailru/jira-plugins-mailrucal/
Плагин поддерживает последнюю версию JIRA (JIRA Server 7.x), а также JIRA6 (JIRA Server 6.3 - 6.4).

**Comment by dariarostshina** [comment]
Ссылка на скриншоты: https://cloud.mail.ru/public/9qjp/dppLNdGDt

**Comment by dariarostshina** [comment]
Плагин позволяет отображать запросы в форме календаря. Продолжительность событий определяется значениями полей запроса.
Особенности данного продукта:
- Построение похожих фильтров, зависящих от даты релиза или сроков задачи, сильно утомляет. Не беда! Множество режимов просмотра календаря позволяют легко показывать задачи в нужный отрезок времени (день, месяц, квартал, timeline).
- Чтобы все ваши важные данные были в одном месте, добавляйте гаджет с календарем на рабочий стол.
- Хотите поделиться планами со своими коллегами или составить график отпусков? Воспользуйтесь функцией расшаривания календаря и в несколько кликов информация будет доступна выбранным пользователям.
- Больше не нужно совершать множество действий для изменения сроков в задаче. Календарь поддерживает функцию Drag & Drop. Просто перетащите задачу на нужную вам дату!
- Чтобы оставаться всегда в курсе событий и не зависеть от вашей JIRA, экспортируйте календарь в одно из приложений: Outlook, iCalendar, iOS Calendar, Google Calendar. Все нужное будет всегда под рукой!

Поддерживаются английский и русский языки интерфейса. Если вы можете помочь в переводе на ваш родной язык, обязательно напишите нам!

Mail.Ru Calendar является open-source проектом, с исходным кодом и планами развития можно ознакомиться здесь: https://github.com/mailru/jira-plugins-mailrucal/

For JIRA Server 6.3 - 6.4 please use 2.4.2.50_JIRA6 version.

**Comment by dariarostshina** [comment]
https://cloud.mail.ru/public/9qjp/dppLNdGDt скриншоты
