### ISSUE TITLE
JQL as filter event don't work

### ISSUE THREAD

**Issue by acasari** [mailru/jira-plugins-mailrucal#52]
I have this JQL:

project="Soporte JIRA y CONFLUENCE" and resolution is EMPTY and assignee=currentUser()

but calendar don't shows issues. If I click Issues in the Calendar definition I get an error in Issue Navigator:

Invalid filter id. Filter id must be a number.

The URL used is:

http://<SERVER>/issues/?filter=project=%22Soporte%20JIRA%20y%20CONFLUENCE%22%20and%20resolution%20is%20EMPTY%20and%20assignee=currentUser%28%29

**Comment by acasari** [comment]
Moreover, I think this is not working even for saved filters either.

**Comment by mashintsev** [comment]
Check out 2.4.1.49 version. In this version some bug in JQL has been fixed. And we will fix showing issues from calendar definition.

**Comment by acasari** [comment]
Thanks but this is JIRA 6.4.12
I rollback to 2.4.0.48_JIRA6 meanwhile.

**Comment by mashintsev** [comment]
Oh, sorry. Use this version 2.4.1.49_JIRA6

**Comment by mashintsev** [comment]
We fixed it in 2.4.2.59_JIRA6 plugin version. You can install it from marketplace.

**Comment by mashintsev** [comment]
Close issue?

**Comment by acasari** [comment]
Closed.
