### ISSUE TITLE
Question about display in Timeline

### ISSUE THREAD

**Issue by acasari** [mailru/jira-plugins-mailrucal#53]
Hi, this is 2.4.0.48_JIRA6 and I see in the timeline View:

![calendar1](https://cloud.githubusercontent.com/assets/562904/14855860/1ab7753a-0c6c-11e6-995c-4b4832d4ffc0.png)

but in the week view it shows:

![calendar2](https://cloud.githubusercontent.com/assets/562904/14855884/37993b02-0c6c-11e6-90a2-119b91864cfb.png)

The issue due date is:

![calendar3](https://cloud.githubusercontent.com/assets/562904/14855913/547540ea-0c6c-11e6-9eb8-e16a3019c5e2.png)

Is the view in the Timeline a bug?

**Comment by mashintsev** [comment]
Hi.
Yes, it's a bug in 2.4.0.48_JIRA6 version. And we already fixed this bug. Just update to the latest plugin version.

**Comment by acasari** [comment]
2.4.2.50_JIRA6 ?

**Comment by mashintsev** [comment]
Yes.

**Comment by mashintsev** [comment]
Sorry, I can't reproduce this problem. And I need more info about your configuration. Please write:

- Calendar's Start and End dates
- Your JIRA default timezone
- Your timezone in JIRA user profile 
- Your OS timezone

PS. Do you need spanish translation for our plugin?

**Comment by acasari** [comment]
I have an issue with Jira and time, so I would put this on hold since that issue might be causing this one. I just would like to confirm what is the expected behaviour in this case, that is, where the line(dot) should point to in the timeline.

Regarding the translation, In my profile I have english as default language, but if you can provide a spanish translation to show days and months that would be great.

**Comment by mashintsev** [comment]
Look at screenshot:
<img width="925" alt="2016-05-05 15 02 15" src="https://cloud.githubusercontent.com/assets/986470/15044070/967ef898-12d2-11e6-81eb-8c489fca603c.png">

**Comment by acasari** [comment]
![5](https://cloud.githubusercontent.com/assets/562904/15061703/a298b326-130e-11e6-8f89-e3d72a4f080a.png)
![4](https://cloud.githubusercontent.com/assets/562904/15061700/a24fee16-130e-11e6-81d1-78e6890beab0.png)
![3](https://cloud.githubusercontent.com/assets/562904/15061704/a2d397ca-130e-11e6-9e91-07949389638c.png)
![2](https://cloud.githubusercontent.com/assets/562904/15061702/a277cfd0-130e-11e6-8c6e-95eff38e2350.png)
![1](https://cloud.githubusercontent.com/assets/562904/15061701/a276a2c2-130e-11e6-8259-86295e436dc2.png)

Attached the screenshots. OS time is the same as JIRA's Systems Info.
I just made a test and created an issue at 10 PM with DueDate May 6th . 
Calendar shows it about 9 PM, wich is due date minus 3 hours = timezone offset. 

![Uploading 6.png…]()

**Comment by mashintsev** [comment]
I find out the problem. And we will fix it in the next release.
