### ISSUE TITLE
Calendar Time off by 1 hour

### ISSUE THREAD

**Issue by lgkevin** [mailru/jira-plugins-mailrucal#54]
I have created a custom field called 'Start Time'. This is the field that is displayed on the Calendar Plugin.  In the ticket itself, the time shows at (for example), 10:00am CST.  However in the calendar, it is displayed as 9:00am CST.  My user profile is set to to the system default of Mexico City (-6:00).

Is there a reason these are different or is it possible to update the calendar settings?  I am running version v6.4.5 of JIRA and version 2.1.1 of the mail.ru.calendar.

Screen shot of the value in the JIRA ticket:
![image](https://cloud.githubusercontent.com/assets/19151882/14957871/5b054d3a-104d-11e6-9a0b-ba536dad3152.png)

Screen shot of the value as displayed in the calendar:
![image](https://cloud.githubusercontent.com/assets/19151882/14957923/8cb01b76-104d-11e6-8a9b-27c76ba24cd1.png)

**Comment by mashintsev** [comment]
Hello.

We already fix this problem. Update to the latest plugin version for your JIRA from Atlassian Marketplace.

**Comment by mashintsev** [comment]
Have you checked your problem on 2.4.2.50_JIRA6 plugin version?
