### ISSUE TITLE
Not able to enter start & end date for the issue.

### ISSUE THREAD

**Issue by Prachiga** [mailru/jira-plugins-mailrucal#55]
Hello,

I want to create a simple calendar to manage holidays of team members. However when I am selecting Range of custom dates option it is not allowing me to do any changes in the calendar. I am currently using JIRA v6.0.4. Below is the screenshot.

![calendar](https://cloud.githubusercontent.com/assets/19186908/15013246/0a8ba766-121c-11e6-9dc3-bc6a226f25ab.png)

Request you to help me to resolve the issue.

Thanks
Prachi

**Comment by andreymolchanov** [comment]
Prachi,
Unfortunately, we don't support the old versions of Mail.Ru Calendar (former Simple Calendar). The best I can suggest is to update JIRA version to minimal version that is supported by Calendar and then update Calendar.
