### ISSUE TITLE
Add issue key as a data attribute to calendar content cells.

### ISSUE THREAD

**Issue by tomikall** [mailru/jira-plugins-mailrucal#59]
Issue key is available only as text content within the content cells. If div.fc-content elements had issue key as a data attribute, it would make it cleaner to operate on issues over the JIRA REST interface as the issue key wouldn't need to be parsed from the text.

**Comment by mashintsev** [comment]
You can find issue key with this expression:
AJS.$('.calendar-event-object').data('event-id')
