### ISSUE TITLE
Getting an error on the newer version of Calendar while clicking on the Itinerary

### ISSUE THREAD

**Issue by UdayaMudigere** [mailru/jira-plugins-mailrucal#62]
I upgraded the calendar to this version 2.5.0.61 and now when we click on an Itinerary, we are getting the following error. See the attached. Please let me know what should be the fix for this.

Thanks
Udaya
[Calendar displaying the Itineraries.pdf](https://github.com/mailru/jira-plugins-mailrucal/files/328059/Calendar.displaying.the.Itineraries.pdf)
[Error displayed while clicking on the Itinerary.pdf](https://github.com/mailru/jira-plugins-mailrucal/files/328060/Error.displayed.while.clicking.on.the.Itinerary.pdf)

**Comment by mashintsev** [comment]
What is your Jira version?

**Comment by UdayaMudigere** [comment]
It is 6.4.12

**Comment by UdayaMudigere** [comment]
Sorry I accidentally selected Close and Comment instead of Comment. We are using JIRA 6.4.12.

**Comment by mashintsev** [comment]
We have fixed problem in [2.5.1.67_JIRA6 version](https://marketplace.atlassian.com/plugins/ru.mail.jira.plugins.mailrucal/versions#b590).

**Comment by mashintsev** [comment]
Do you have the problem after update?
