### ISSUE TITLE
Create new calendar doesn't bring anything up

### ISSUE THREAD

**Issue by smorris1** [mailru/jira-plugins-mailrucal#65]
I've recently downloaded the mail ru plugin to our JIRA environment. 

One piece of functionality don't seem to work. If I click on the  "Add Calendar" button and the "Create New" nothing happens. 

There doesn't appear to any logging. 

Sorry I don't have a great deal of information about this. If I find any further clues as to way this is going wrong I will add it to this issue.

![capture_create_new_calendar](https://cloud.githubusercontent.com/assets/20474993/16871678/2fbc2c8a-4a80-11e6-802b-b8e2c15c9ba4.JPG)

**Comment by smorris1** [comment]
I've also installed a previous version - 2.5.2.69 and I still have the same problem. Also I've noticed there isn't any output in the browser developer logs when I attempt to click on "Create New" so it behaves like there isn't any button there at all.

**Comment by mashintsev** [comment]
Hi.
What JIRA version do you use? Copy all messages in browser console after page loaded.

**Comment by smorris1** [comment]
We use version 7.1.2

**Comment by smorris1** [comment]
![capture_create_new_calendar_console_error](https://cloud.githubusercontent.com/assets/20474993/16877237/0c585bdc-4a9f-11e6-86f4-3a0c8db8c307.JPG)

**Comment by mashintsev** [comment]
I fixed a potential problem. Can you check this beta version(attached) on your JIRA?
[mailrucal-2.5.4.73.jar.zip](https://github.com/mailru/jira-plugins-mailrucal/files/366191/mailrucal-2.5.4.73.jar.zip)

**Comment by smorris1** [comment]
Thanks very much, that's fixed the issue, Can this version be released officially?

**Comment by mashintsev** [comment]
Yes. I wanted to make sure it solves the problem.

**Comment by smorris1** [comment]
Ok, thanks for the very fast response.
