### ISSUE TITLE
Drag & Drop in Month View not working since 2.5.4.73

### ISSUE THREAD

**Issue by kwilium** [mailru/jira-plugins-mailrucal#66]
Hello guys!

Since version 2.5.4.73 the Drag & Drop of issues in month view isn't working anymore. So, is there a special shortcut or key combination to get it working?

Many Thanks in advance,
Marko

**Comment by mashintsev** [comment]
Hi, Marko.

Please provide more info.
1) Which date fields do you choose for calendar? Maybe they are not editable.
2) In other view does D&D work?
3) Before  version 2.5.4.73 does D&D work for this calendar?

**Comment by kwilium** [comment]
Hi mashintsev,

sure.
1) DueDate and StartDate (StartDate is a custom field)
2) no, it won't work in any views
3) of course, it worked like a charm before

**Comment by mashintsev** [comment]
Are events transparent and have a red box?

You can't d&d events if
1) Start date is after end date.
2) Start date is not defined.
3) S tart and end fields are editable and user have permission to edit them.

**Comment by kwilium** [comment]
ok I got it.

There must be a start date. So that's new.
Because, most of time I use only the due date - so that's the failure.

**Comment by kwilium** [comment]
i tested it now with start date an end date. worked now. but when i move a task to another day, then the default start date is one day before the end date.
that's not so good...so is there a way to get the function back working if no start date is choosen?

**Comment by kwilium** [comment]
hi there,

that is the status of this issue? are u already working on it?


thanks in advance

**Comment by kwilium** [comment]
good morning guys,

so, this issue still exists. When we will receive a fix for it?

thanks,
marko

**Comment by mashintsev** [comment]
Check out version 2.5.8.77.

**Comment by kwilium** [comment]
hi there,

late but this bug is gone! thanks guys.
