### ISSUE TITLE
post jira server 7.1.9.upgrade issue

### ISSUE THREAD

**Issue by dwmason78** [mailru/jira-plugins-mailrucal#68]
Hi,
After our upgrade to Jira Server 7.1.9, i can no longer configure a new calendar. Screenshot attached:  

I uploaded a screenshot, but the "configure" screen looks something like this:

ru.mail.jira.plugins.calendar.gadget.config.calendars

ru.mail.jira.plugins.calendar.gadget.config.calendars.description
ru.mail.jira.plugins.calendar.gadget.config.view
ru.mail.jira.plugins.calendar.gadget.config.weekends
ru.mail.jira.plugins.calenda

r.gadget.config.weekends.description
gadget.common.refresh.label
gadget.common.refresh.description
 

Any ideas as to what can be done to get it back to normal?

Dave
![mail ru](https://cloud.githubusercontent.com/assets/21206845/17910711/1b260222-6958-11e6-926e-b92c6beb2382.jpg)

**Comment by mashintsev** [comment]
It's JIRA 7.1.* problem. Look [here](https://confluence.atlassian.com/jirakb/how-to-fix-gadget-titles-showing-as-__msg_gadget-813697086.html) to fix it.
