### ISSUE TITLE
Why is the 'ReleaseDue' attribute of the JIRA ticket not available for 'start event' Mail.RU calendar property?

### ISSUE THREAD

**Issue by LievenRoelens** [mailru/jira-plugins-mailrucal#73]
When creating a Mail.RU calendar you need to select an attribute for the start event.
I'd like to select the ReleaseDue attribute (= release date of the fix version) as start event. This seems not to be possible. With this attribute I can add issues that will be delivered to a customer to the calendar as the release date of the fix version is the date the version gets delivered to a customer.

**Comment by LievenRoelens** [comment]
Version the issue is reported on: 2.5.6.75 for JIRA7

**Comment by LievenRoelens** [comment]
ReleaseDue is a calculated read only custom field introduced for reporting purposes.

**Comment by mashintsev** [comment]
Is your custom field 'DateField'? We choose only DateField  for event start and end.
