### ISSUE TITLE
2.5.6.75 for JIRA7

### ISSUE THREAD

**Issue by hpmedia** [mailru/jira-plugins-mailrucal#74]
Could you please update your repo to add v2.5.6.75 for JIRA7?
We have added some custom fields in our calendar to give us more information about the issues and we would like to implement them in the newest version as well.

Or perhaps, could you add this as a feature?
We've added
- Issue title
- Issue status

We use the calendar for change management(CM) and deviations(AVVIK), see attached screenshot.
![mailru](https://cloud.githubusercontent.com/assets/1403302/19260571/eeb054a0-8f8a-11e6-8d13-aa1550f7d999.png)

**Comment by mashintsev** [comment]
Where can I see your calendar version?
Issue title is already exist in event.

**Comment by mashintsev** [comment]
Duplicate for #64
