### ISSUE TITLE
Dashboard widget is only available to some users

### ISSUE THREAD

**Issue by SyxALM** [mailru/jira-plugins-mailrucal#77]
We have configured dashaboard with the Mail.Ru gadget but only some users are able to see the calendar in Dashboard and some are not. However same users can see the same calendar directly from calendars option. 
![calendar permission](https://cloud.githubusercontent.com/assets/12660579/20304798/2c0a653c-ab58-11e6-8ed5-c905914bde4d.png)

**Comment by fil-daimler** [comment]
I have the same issue here! Any help is appreciated!

I have 4 calendars and all have the permission to the group of all logged in users. The dashboard that uses the gadget is shared to all logged in users.
