### ISSUE TITLE
user cannot see mail ru. calendar (only admin can see) 

### ISSUE THREAD

**Issue by savitreehongvihock** [mailru/jira-plugins-mailrucal#78]
Admin's created the mail.ru calendar but user's cannot see (show blank screen) please help us investigate why user's cannot see. Any we would allow a premission?  
Screenshot 1 user's
![screenshot-mail_ru](https://cloud.githubusercontent.com/assets/23518054/20380320/e4242c94-acd3-11e6-81c3-391fbabd6ca8.jpg)

Screenshot 2 admin's
![screenshot2-mail_ru](https://cloud.githubusercontent.com/assets/23518054/20380366/2d721ac8-acd4-11e6-9aa4-ca681991b768.jpg)
 and user's cannot create mail.ru calendar when create caledar dashboard will show blank.
![screenshot3-blank calendar](https://cloud.githubusercontent.com/assets/23518054/20380703/479477b4-acd6-11e6-8281-e819b9bd0c6a.jpg)

**Comment by mashintsev** [comment]
Go to Permission tab in Calendar Settings dialog. And add users who must see these calendars. By default only created user and admin can see calendar.
