### ISSUE TITLE
Add Mail.Ru in Confluence (MACROS)

### ISSUE THREAD

**Issue by DanteBRSP** [mailru/jira-plugins-mailrucal#80]
A help.
I added the JIRA Mail.Ru gadget in Confluence, but when I try to add it to a page, it throws an error:
The resource could not be found (/rest/mailrucalendar/1.0/calendar/all)
Can you tell me that I'm doing something wrong?

I followed the steps in this link:
https://confluence.atlassian.com/doc/registering-external-gadgets-204050482.html

**Comment by mashintsev** [comment]
You need set Base URL for Gadget. Like this - http://example.com/jira
