### ISSUE TITLE
Ability to create events as Jira issues from calendar screen

### ISSUE THREAD

**Issue by bamuhrez** [mailru/jira-plugins-mailrucal#83]
As a Jira user, I want to be able to create new events as issues within project from within calendar screen/view.

**Comment by mashintsev** [comment]
Why do you not use default JIRA create issue dialog? And how do you want create issues in calendar?

**Comment by bamuhrez** [comment]
Hi,
Sorry, I Just saw your comment. 
This requirements is needed when we want to use Jira Calendar as the main interface for some of our users. Where they just enter meetings related entries. They don't want to create issues from Jira create issue button.

The scenario is t:
1. Double click on day in the calendar 
2. A pop screen screen will show 
3. The User will enter only summary, start time and end time. 

This scenario will almost make this add on a complete calendaring solution within Jira.

Regards
