### ISSUE TITLE
Can only display 10 entries on a single date

### ISSUE THREAD

**Issue by leardley** [mailru/jira-plugins-mailrucal#85]
HI
One of my users is experiencing a couple of issues with the calendar - hoping you can help identify whether these are bugs or user error.

1. Unable to display more than 10 entries on a single date

Is this a configurable limit - or a hard limit in the calendar

Thanks
Lauren

**Comment by mashintsev** [comment]
Hi.
What time period(month, week...) does user use the display? Could you attach a screenshot?

**Comment by leardley** [comment]
HI

Thanks for replying – it looks like he is accessing over a week:

[cid:image001.png@01D26B1F.DB8FAC70]

**Comment by mashintsev** [comment]
Can you attach at GitHub issue page? Because through email it isn't attached.

**Comment by leardley** [comment]
![jira calendar](https://cloud.githubusercontent.com/assets/25011748/21930345/8a652898-d98d-11e6-87ed-61d4475378d1.png)

**Comment by leardley** [comment]
Should be attached now - cheers

**Comment by mashintsev** [comment]
In this view you can scroll in timeline by mouse. Click and hold on the empty space inside timeline and move mouse up or down.

**Comment by leardley** [comment]
Thanks for the reply - just a further follow-up from the user.  Is it possible to configure how many values that you see in the view as an alternative to scrolling?

Thanks,
Lauren

**Comment by mashintsev** [comment]
Unfortunately, No.
