### ISSUE TITLE
Trying to get JIRA issues into Confluence using the Gadget.

### ISSUE THREAD

**Issue by dmpgordon** [mailru/jira-plugins-mailrucal#91]
I have setup the application links and added the individual Gadget Specification (of http://jirasd:8080/rest/gadgets/1.0/g/ru.mail.jira.plugins.mailrucal:mailru-calendar-gadget/ru/mail/jira/plugins/calendar/gadget/calendar-gadget.xml) 

When I try to load in Confluence it says ‘The resource /rest/mailrucalendar/1.0/calendar/all, cannot be found.

Any ideas or suggestions wellcome

**Comment by mashintsev** [comment]
Can you upload or send to me calendar-gadget.xml file. My email i.mashintsev@corp.mail.ru

**Comment by dmpgordon** [comment]
Hi Ivan,

Thanks for your prompt response.  See attached

Regards

Dave


________________________________

**Comment by dmpgordon** [comment]
Hi Ivan,
I think I previously missed attaching the file - see attached
Re
[calendar-gadget-xml.txt](https://github.com/mailru/jira-plugins-mailrucal/files/853940/calendar-gadget-xml.txt)

gards
Dave

**Comment by mashintsev** [comment]
Hi. Today we release new version with Confluence support.

**Comment by dmpgordon** [comment]
Works perfectly.
Many thanks
Regards
Dave
