### ISSUE TITLE
Drag-and-drop sets the date to 1 day off

### ISSUE THREAD

**Issue by myicicle** [mailru/jira-plugins-mailrucal#97]
If I drag and drop an issue in the calendar to, say, 4/29, then the issue's date will change to 4/28 in JIRA. It's 1 day off.

**Comment by seanmkeating** [comment]
This seems to happen when event start and event end dates are the same field and that field is date-only (using date/time fields doesn't have this problem)

**Comment by myicicle** [comment]
Oh cool! So we can ease the Comms team to using this calendar.

I’m also going to ease them into new email templates AND THEN slowly talk them into the new content builder, which is going to be easier anyway. But I want to first learn their ways with the email templates, and then I’ll know better how to approach this issue with them.
